### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by babasaad1909** [shalzuth/TemSharp#12]
![Unbenannt](https://user-images.githubusercontent.com/60584531/73615697-a203d980-460a-11ea-88be-1695bcc90b80.PNG)
Maybe anyone can help me.^^ 
Want to test the bot and will donate for sure if its work because why not.

**Comment by shalzuth** [comment]
Try relaunching. This is fixed in last update.

**Comment by babasaad1909** [comment]
Still the Same Problem.
Also redownloaded the file but nothing changed.
Thank u for the fast reply ^^

**Comment by shalzuth** [comment]
Is there a TemSharp folder created by the .exe? Can you delete it?
